# Generated by Django 5.2 on 2025-04-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('porcentaje_necesidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('porcentaje_deseos', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('porcenta_ahorros', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
